### Stand Mixer Challah (makes 2 loaves) 
#### Veganized, originally from the kitchen of Margot Benstock

**Dry**
* 1/2 oz. Flischmann’s Rapid rise yeast (in a packet)
* 1/2 Tbsp salt 
* 5 cups bread flour 
* Sifted Sesame seeds  

**Wet**
* 1/4 cup coconut oil
* 3 Tbsp maple syrup
* 1/3 cup coconut milk
[//]: # TODO: Move below to Step 1 and heat according to Benstock version
*Combine wet ingredients and whisk, adding water until you have 2 cups of liquid*

1. Put 2 cups flour aside. Put the other 2 cups of flour in the mixer. Mix for one minute and add wet ingredients. Mix at high speed for 3 minutes.
2. Add 1 Tbsp at a time of flour to the dough. You may incorporate rest of flour by kneading it on table.
3. Put dough in greased 4 qt bowl, covered for 60 - 90 minutes. 
4. Braid the dough. Brush with oil.
5. Let rise until twice the size. Glaze with mixture of 1 Tbsp oil and 1 Tbsp coconut milk.
6. Bake at 350 degrees for 40 minutes.

*1st rise: 60-90 minutes*  
*2nd rise: 60 minutes*

### Bread Machine Challah (makes 2 Challahs) 
#### From the kitchen of Susan LeVine
*Allow 3 hours*    

* 1 cup Water
* 4 Tbsp Sugar
* 2 tsp Salt
* 2 Eggs
* 1 Egg (to glaze top of challah)
* 4 cups Bread Flour
* 2 Tbsp Margarine
* 1 1/2 tsp rapid rise Yeast
* Sesame seeds    

1. Measure first six ingredients into dough machine in the order above. After adding flour, make impression in center and put yeast in hole. 
2. Cut-up margarine and place in corners of bread machine pan. 
3. Set machine on “Dough” cycle (mine takes 1 hour and 20 seconds). 
4. Pull dough out onto lightly floured surface in a rectangular shape and cut with very sharp knife into even strips, about 9-12” long for braiding.  
*HINT: a drop of water will stick braided ends together.*  
5. Braid dough, secure ends and allow loaf to rise 1 hour.
6. Brush with beaten egg and sprinkle with sesame seeds. Bake at 350 degrees for 25-30 minutes.
